### ISSUE TITLE
Import translations and update translators dialog

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#10]

**Comment by javiersantos** [comment]
Maybe this IntelliJ plugin by OneSky is useful :+1: https://github.com/onesky/plugin-intellij

**Comment by jahirfiquitiva** [comment]
Thanks @javiersantos

**Comment by M2ck** [comment]
What news about it? Please merge translations, many languages are fully translated.

**Comment by jahirfiquitiva** [comment]
@M2ck I will merge them for next update.
