### ISSUE TITLE
Please update translation files.

### ISSUE THREAD

**Issue by frowhy** [jahirfiquitiva/IconShowcase#102]
Please update translation files, now there is a language translation progress in 14 countries reached 100%

**Comment by jahirfiquitiva** [comment]
Hey you're right, but some languages have out-of-date translations

Bengali: 4 phrases to update.
Chinese Simplified: 3 phrases to update.
Turkish: 1 phrase to update.

Until they are completely finished, I will stay with the already included 9 languages.

Stay tuned about it.

**Comment by SubhrajyotiSen** [comment]
Bengali translations have been updated.

**Comment by jahirfiquitiva** [comment]
Thanks @SubhrajyotiSen
