### ISSUE TITLE
Fix dialog not appearing when license check is succesful

### ISSUE THREAD

**Issue by simonmartinov** [jahirfiquitiva/IconShowcase#105]
Fix License Check Dialog to appear on the first launch of the app.
Introduce some banners linked that we can edit on the main home screen of the apps for promoting our other work,

**Comment by jahirfiquitiva** [comment]
You can already promote your apps in home screen.
You can add the list of apps in `home_configuration.xml`

**Comment by AllanWang** [comment]
Is this still an issue?

**Comment by jahirfiquitiva** [comment]
I can't really reproduce it @AllanWang ... let's wait to see how the new update goes.
