### ISSUE TITLE
Requests checkbox not showing

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#110]
Checkboxes don't show if layout is setup from task.

(Text color issue is fixed already)

**Comment by jahirfiquitiva** [comment]
Happens when the section content is [setup in task code](https://github.com/jahirfiquitiva/IconShowcase/blob/master/library/src/main/java/jahirfiquitiva/iconshowcase/tasks/LoadRequestList.java#L175).

Result:
Loss of the text and checkbox style for no apparent reason.

Here's a preview of the issue.
Text is white, checkboxes are teal when checked and white when not.

![screenshot_20160818-233029](https://cloud.githubusercontent.com/assets/10360816/17799228/64f57dc8-659e-11e6-97ce-66d0cfc7d573.png)

**Comment by AllanWang** [comment]
I'm going to redo the tasks and make them all nonstatic so things will probably change.

**Comment by jahirfiquitiva** [comment]
With Butler it seems to be working fine
