### ISSUE TITLE
Replace logging with timber and avoid logging in production

### ISSUE THREAD

**Issue by AllanWang** [jahirfiquitiva/IconShowcase#117]

**Comment by jahirfiquitiva** [comment]
What's the advantages of using Timber?

Btw, people can disable logs by setting "debugging" to false.

**Comment by AllanWang** [comment]
Among a lot of formatting features, timber tries to add the class name withihn the log, so there is no need for you to write your own tag (which you are doing with context). Logging also affects performance so it should be used minimally on release builds. And especially since you are targetting users who don't want to develop, there isn't much point in outputting much of the logs. Your boolean is used for things like figuring out appfilter errors, but I'm talking about the rest of the logging used in this project.

**Comment by jahirfiquitiva** [comment]
Don't get me wrong. I just don't want the library to use other libraries, that the main app won't really need.
