### ISSUE TITLE
Fix light theme

### ISSUE THREAD

**Issue by AllanWang** [jahirfiquitiva/IconShowcase#118]
Status bar and nav bar are both light grey

**Comment by jahirfiquitiva** [comment]
People can set the navbar color they want for the theme.

**Comment by AllanWang** [comment]
You intended the navbar to be light by default? Even though the nav items are also white?

**Comment by AllanWang** [comment]
This is your default look. I think it's an issue

![capture](https://cloud.githubusercontent.com/assets/6251823/17829473/d7f45dc8-6664-11e6-8f62-bf4d8d61fcc8.PNG)

**Comment by jahirfiquitiva** [comment]
That's the color I set for navbar, yeah.

It can be changed with
"light_theme_navigation_bar" and "dark_theme_navigation_bar" colors
