### ISSUE TITLE
Create Config Interface for Reading Resources

### ISSUE THREAD

**Issue by AllanWang** [jahirfiquitiva/IconShowcase#119]
This will take care of most getResource methods. Please withhold from renaming any other xml items for now until this is closed.

**Comment by jahirfiquitiva** [comment]
How far is this from completion? I think is an improvement that can be done later, when all the other important or high priority issues are fixed.

I appreciate your help, but I think actual issues should be fixed before doing this kind of improvements.

Hope you understand. Thanks for the help Allan :)

**Comment by AllanWang** [comment]
I just finished the frame and I changed the way it works so a lot of the resources will still take in the id. You can take a look at the list of methods in the config file. I'll implement it later but for now feel free to change the resource names.
