### ISSUE TITLE
Fix AltWallpaperViewerActivity FAB and Snackbars margin

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#120]
The FAB and snackbars go behind the navigation bar. The current implemented code to add margin to them doesn't seem to work in tablets, although it does in phones.

Tested on a Nexus 7 2013 in emulator.

Result:
![device-2016-08-20-011029](https://cloud.githubusercontent.com/assets/10360816/17832344/3528e584-66c6-11e6-8d54-16dd12e61ab6.png)
![device-2016-08-20-011236](https://cloud.githubusercontent.com/assets/10360816/17832345/352e2526-66c6-11e6-8417-46f45dff27f0.png)

**Comment by AllanWang** [comment]
It's because you made the view draw under the navigation bar. There was a library that polar used that dealt with this issue by adding padding to the frame layout I believe.

**Comment by jahirfiquitiva** [comment]
**Android 4.2.2 Phone Landscape**
![device-2016-08-20-212652](https://cloud.githubusercontent.com/assets/10360816/17835087/d9e1422e-6720-11e6-8060-0c9e9bc10d92.png)



**Android 6.0.1 Phone Landscape**
![screenshot_20160820-174051](https://cloud.githubusercontent.com/assets/10360816/17835092/e9316aba-6720-11e6-9190-4703fe91c37c.png)

**Comment by jahirfiquitiva** [comment]
## I REALLY NEED HELP :(

**Comment by AllanWang** [comment]
I don't know how you've changed everything but have a look at something like this

http://stackoverflow.com/a/28341624/4407321

preferably, keep it simple rather than adding a lot of displaymetric changes

**Comment by jahirfiquitiva** [comment]
@AllanWang 
Just implemented that solution, but mini fabs margins are still wrong :(

**Comment by jahirfiquitiva** [comment]
Maybe the only fix is to use a FAB library that is not design support one.

**Comment by AllanWang** [comment]
Just leave this for now. I'll take a look later

**Comment by jahirfiquitiva** [comment]
Fixed by @AllanWang
