### ISSUE TITLE
Make a java file that generates other xml's for the icon pack

### ISSUE THREAD

**Issue by AllanWang** [jahirfiquitiva/IconShowcase#123]
By this I'm referring to the appmap, drawable, and perhaps icon_pack xml. Hopefully it can remove duplicates from appfilter and show the same debug notices IconShowcase shows now.

Instead of making it a jar, we can make it a java file with booleans to toggle its functionality and a string input for the directory so it will be easier to change. Plus users can run it directly from android studio anyways.

If we do this we can make a tools folder and store it there.

**Comment by PDDStudio** [comment]
Maybe [Lumax](https://github.com/mddanishansari/Lumax) can help here?

**Comment by AllanWang** [comment]
Interesting. I wonder what they mean by the drawable names not matching, but that seems viable.

**Comment by AllanWang** [comment]
@jahirfiquitiva done or no?

**Comment by jahirfiquitiva** [comment]
@AllanWang ... It isn't done yet. I have some ideas in mind, just need to find the time to make it happen. If you want to help, that's welcome :)
