### ISSUE TITLE
Icon request task not filtering out already themed apps

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#127]
Maybe read the file from raw folder instead of assets? @AllanWang

**Comment by AllanWang** [comment]
Not a bug. I had the TODO written that you need to specify the location. I think we should move it to xml instead of raw since no launcher reads it from raw anyways (from my knowledge)

**Comment by jahirfiquitiva** [comment]
No launcher reads the one in raw folder, but was the fix for duplicated items and other things.
Unless it's 100% sure that it will work being either in assets or xml folder, I don't encourage the location change.

**Comment by AllanWang** [comment]
Why would moving it cause an issue? I can actually parse it if it's in xml

**Comment by jahirfiquitiva** [comment]
I'm just saying I had the issue before and don't want to see it again. If it's working fine, the go ahead. No problem. Thanks for your work.

**Comment by AllanWang** [comment]
I've added it so it'll take the appfilter.xml file (in the xml folder). This still needs testing though
