### ISSUE TITLE
Add more device info in request email

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#131]
Like here:
https://github.com/jahirfiquitiva/IconShowcase/blob/master/library/src/main/java/jahirfiquitiva/iconshowcase/utilities/Utils.java#L206

**Comment by SubhrajyotiSen** [comment]
What kind of additional device info are you looking for?

**Comment by jahirfiquitiva** [comment]
@SubhrajyotiSen

The thing is we starting to implement a new library, and its code needs to be modified.

This was just like a reminder or TODO for @AllanWang

Thanks.

**Comment by AllanWang** [comment]
This is no longer needed for the request tool since everything is handled in Butler. You can keep it there for now just so I can see it in case I need to change anything.

**Comment by jahirfiquitiva** [comment]
@AllanWang

Yeah, that was my purpose. Showing the info I expect Butler to add in email content.

Thanks for the help.
😊

**Comment by jahirfiquitiva** [comment]
Let's keep this open until is implemented, just as a reminder. ;)

**Comment by AllanWang** [comment]
Is this not already added? Hm

**Comment by jahirfiquitiva** [comment]
@AllanWang I don't think so, but maybe I'm wrong. Is what I can see from [here](https://github.com/AllanWang/Butler/blob/master/library/src/main/java/com/pitchedapps/butler/library/icon/request/IconRequest.java#L526)

**Comment by jahirfiquitiva** [comment]
I think only app info (version name and code) is missing. This is useful to recognize when people use old pirate apps to request icons.

**Comment by AllanWang** [comment]
[Added](https://github.com/AllanWang/Butler/commit/297596baaccf49fcd940d8c3558b61c3182cf46d)

**Comment by jahirfiquitiva** [comment]
Thank you so much Allan :)
