### ISSUE TITLE
Make sure CollapsingToolbar is only expandable in Main/Home section

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#132]
The CollapsingToolbar can be expanded in all sections after configuration changes.

Not sure if related to Capsule implementation, or if support 24.2.0 library.

**Comment by AllanWang** [comment]
You used to call collapse and expand at the start and stop of every fragment, as well as the activity. I changed it to only switch after fragment switches from the activity. This should easy to fix.
