### ISSUE TITLE
Add support for Polar Request Manager

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#137]
Just for the future. Not for version 2.0.

**Comment by AllanWang** [comment]
What does this mean?

**Comment by jahirfiquitiva** [comment]
Make the requests work with [Aidan Follestad's Polar Request Manager](https://polar.aidanfollestad.com/)

I think Aidan made an API or something.


This means, users with Polar Request Manager accounts could use it even when using IconShowcase as their dashboard.

**Comment by AllanWang** [comment]
He did make an API, but are you sure he wants it to be used in other apps?

**Comment by justinkruit** [comment]
Did you already talk with Aidan about this?

**Comment by AllanWang** [comment]
No. But I'm saying that if you want to add it you might want to talk to him

**Comment by justinkruit** [comment]
@AllanWang question was mostly meant to Jahir, but I can talk to Aidan if needed, that won't be a problem

**Comment by AllanWang** [comment]
Oops my bad. Misread the name and thought you were Jahir

**Comment by justinkruit** [comment]
😂😂😂

**Comment by jahirfiquitiva** [comment]
I'm confident he will allow it. I just asked him... Waiting for a reply.

**Comment by jahirfiquitiva** [comment]
Aidan said [he wanted to keep it private for now](https://github.com/afollestad/polar-dashboard/issues/137)

I will ke issue open, as a future feature.

I had no rush on this, and as you can see milestone is 3.0 so I didn't planned to have it anytime soon.
