### ISSUE TITLE
RepelloMaxima

### ISSUE THREAD

**Issue by Technologx** [jahirfiquitiva/IconShowcase#145]
Where is this and how do I make my own so I can add it to the library?

**Comment by jahirfiquitiva** [comment]
Is a new library for license check purposes. The aar file is in project source, but I won't allow anyone use it until the next public release/update of IconShowcase.

**Comment by Technologx** [comment]
Alright well how could I edit the aar file?

**Comment by jahirfiquitiva** [comment]
Why would you need to edit it?

As I just said, nobody is allowed to use the aar outside of the IconShowcase library for now.

Use [PiracyChecker library](https://github.com/javiersantos/PiracyChecker) instead.
