### ISSUE TITLE
SDK location not found when I import the project from gradle. using windows 10

### ISSUE THREAD

**Issue by vampothika** [jahirfiquitiva/IconShowcase#147]
SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable﻿

**Comment by jahirfiquitiva** [comment]
@vampothika 
That issue is not related to IconShowcase. You must properly setup the SDK and Android Studio before working on IconShowcase. I won't explain that since you can find lots of info all around the web.

**Comment by jahirfiquitiva** [comment]
@vampothika 
Also, using the library source means you won't get any help from me, as stated [here](https://github.com/jahirfiquitiva/IconShowcase#library-source). If you don't have enough experience with android development, I suggest to use the [dashboard source](https://github.com/jahirfiquitiva/IconShowcase-Dashboard).
