### ISSUE TITLE
Loading kwgt widget from app does not work

### ISSUE THREAD

**Issue by marcogenovese** [jahirfiquitiva/IconShowcase#150]
![inkedscreenshot_20170626-023402_li](https://user-images.githubusercontent.com/27960197/27521114-0f8055f0-5a19-11e7-9b86-5955cce2244f.jpg)
![inkedscreenshot_20170626-023514_li](https://user-images.githubusercontent.com/27960197/27521117-1f800ed2-5a19-11e7-8527-53bc1caf99fa.jpg)
![inkedscreenshot_20170626-023330_li](https://user-images.githubusercontent.com/27960197/27521123-29bc9564-5a19-11e7-8cda-d6b97a9e06bb.jpg)

**Comment by jahirfiquitiva** [comment]
I don't understand. Can you elaborate on this?

**Comment by marcogenovese** [comment]
For example. Open iconshowcase, go to kustom section, tap a widget, choose a kwgt base (or canvas) i don't know how to call it. If the base is a blank widget Kwgt goes to the installed screen ignoring the upload, if the base is a widget already set kwgt freezes

**Comment by jahirfiquitiva** [comment]
@marcogenovese 
Still don't get it. I don't really use KWGT. Can you record a video or something?

**Comment by frmz** [comment]
I can look into this

**Comment by jahirfiquitiva** [comment]
Wow, thank you so much @frmz 😁

**Comment by jahirfiquitiva** [comment]
@frmz 
Can you please look into this but in [Kuper](https://github.com/jahirfiquitiva/Kuper/) ??
Thanks in advance
![bitmoji](https://render.bitstrips.com/v2/cpanel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-f1a30f5f-4907-483f-874a-54b05c8475ab-v1.png?transparent=1&palette=1&width=246)
