### ISSUE TITLE
Status bar is not darkened when in demo mode

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#55]
When using Marshmallow demo mode, the app shows the status bar the same color as primary color, which isn't the right color.

I don't know if it's app related or it's because of MaterialDrawer or Materalize libraries.

**Comment by julianostarek** [comment]
What is demo mode? @jahirfiquitiva

**Comment by jahirfiquitiva** [comment]
@julianostarek 

Slide the notifications panel down, then long press the gear icon until it starts rotating, or you get a toast. Then go to settings -> SystemUI tuner -> demo mode

Or, go to Settings -> About device -> Press "Build date" a lot of times.
