### ISSUE TITLE
Add Google Play license check

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#63]
The current license check isn't so good. This is pretty good. (I just don't know how to do it).

http://developer.android.com/google/play/licensing/overview.html

**Comment by Vextil** [comment]
The Google Play license check is only for paid apps or free ones that use the APK expansion library. This method won't work for IconShowcase.

**Comment by jahirfiquitiva** [comment]
Well, it isn't really needed either.
