### ISSUE TITLE
Center splash screen icon properly in landscape mode

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#70]
![screenshot_20160206-191334](https://cloud.githubusercontent.com/assets/10360816/12870706/1f343e22-cd1f-11e5-9684-cce290578d56.png)

**Comment by TheAndroidMaster** [comment]
If you aren't already doing this, you should create a 9 patch drawable and set it as the android:windowBackground in the style for the splash screen. It should center properly and will load a lot faster. There's a 9 patch generator here if you need it https://romannurik.github.io/AndroidAssetStudio/nine-patches.html

**Comment by jahirfiquitiva** [comment]
I'm already using a .9.png
But if I set the windowBackground to that icon, wouldn't it make it fill the screen?

**Comment by TheAndroidMaster** [comment]
@jahirfiquitiva It depends on how you set up the 9 patch. You could add a bit of padding to prevent this, but I think since it doesn't fill the screen now it should be fine.

**Comment by asdfasdfvful** [comment]
If you add padding to the 9 patch, that will make it look weird in portrait mode. I don't know if there's a way to hide the navbar while this is happening (that way it'll look centered), or you could just make the navbar the same color like so:

![screenshot_20160304-154409](https://cloud.githubusercontent.com/assets/6251823/13539913/6cfa1db8-e221-11e5-966b-af43818fcbf7.png)
