### ISSUE TITLE
Appfilter corrector lag

### ISSUE THREAD

**Issue by asdfasdfvful** [jahirfiquitiva/IconShowcase#78]
1. If there are many lines in the appfilter, it can take many seconds for the loading process to finish
2. Might be because I have appfilter.xml files in my assets folder (for theming), but the appfilter says that every line I have is a duplicate (with 0 count)

Perhaps make the logging dependent on BuildConfig.DEBUG or toggleable

**Comment by jahirfiquitiva** [comment]
Can you send me a copy of your appfilter xml please?

**Comment by asdfasdfvful** [comment]
[Here](https://github.com/asdfasdfvful/Material-Glass/blob/master/Material-Glass/src/main/res/raw/appfilter.xml).

And this isn't even a long appfilter yet. I have ones 10 times longer than this
