### ISSUE TITLE
Changelog dialog not showing after new versions

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#79]

**Comment by amin947** [comment]
Hi
What did you change to solve this problem?

**Comment by jahirfiquitiva** [comment]
I won't explain changes. Either update to latest versions of IconShowcase, or check the commits to find the answers.

If you have errors updating, then post in the community and I will try to help. But that's all I will do.

**Comment by amin947** [comment]
I didn't see anything regards #79 on the commits.

**Comment by jahirfiquitiva** [comment]
A lot of commits have been done. You will have to check all of them and find the answer, or update to latest IS version.
