### ISSUE TITLE
Reduce RAM/Memory consumption/usage, to the lowest possible

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#81]

**Comment by HeinrichReimer** [comment]
Possible way would be to make use of `WeakReference<>` where possible to make garage collection more efficient

**Comment by HeinrichReimer** [comment]
Storing `Context` objects can blow up the app memory a lot so storing them as `WeakReference<Context>` instead of `Context` make a big difference especially on low memory devices.
