### ISSUE TITLE
Hiding App Icon doesn't seem to work well

### ISSUE THREAD

**Issue by AllanWang** [jahirfiquitiva/IconShowcase#82]
At least from what I see now, packageName in componentNameString must be the name of the parent of the class, not the package name itself. If the package name is changed in the build gradle, it won't work well. Consider making this a string that can be customized?

This issue affects both the SettingsFragment and LauncherIconRestorerActivity

Fix:

`final String packageName = Utils.getAppPackageName(getApplicationContext());
        final String componentNameString = "com.pitchedapps.material.glass.HomeActivity"; //TODO fix in iconshowcase; make this a customizable string; not just the HomeActivity part`

**Comment by jahirfiquitiva** [comment]
And is your HomeActivity inside `com.pitchedapps.material.glass` package?

**Comment by asdfasdfvful** [comment]
Yes. For you it should be the jahir line, and this won't change if people continue using it as a library.

**Comment by jahirfiquitiva** [comment]
Can you try with the latest changes, please?

**Comment by asdfasdfvful** [comment]
Which commit contains the change? I haven't rebased my app to your library yet as I needed to modify the homefragment before, but I can take a look at what you did. I also gave you access to my own repo so you can see how I did some things.

**Comment by jahirfiquitiva** [comment]
https://github.com/jahirfiquitiva/IconShowcase/commit/84ac0103d122ea3d276d625bfd90c94c496a0d82

**Comment by jahirfiquitiva** [comment]
@asdfasdfvful

Btw, I just checked your code and you left HomeActivity and that activity is not in the java folder

**Comment by asdfasdfvful** [comment]
My HomeActivity is gitignored as it contains my PUBKEY. Even though my repo is private, I make it public from time to time. It's in the java folder though.

**Comment by jahirfiquitiva** [comment]
Ah, ok. No problem. Then ignore my last comment and try the changes in SettingsFragment from the commit I linked you previously (84ac010)

**Comment by jahirfiquitiva** [comment]
@asdfasdfvful

Did it work?

**Comment by AkshayChordiya** [comment]
You can enable disable showing app icon using

For Enable
`
getPackageManager().setComponentEnabledSetting(
					new ComponentName(packageName, packageName+ "COMPONENT_NAME"),
					PackageManager.COMPONENT_ENABLED_STATE_ENABLED,
					PackageManager.DONT_KILL_APP);
`
Disable:
getPackageManager().setComponentEnabledSetting(
						new ComponentName(packageName, packageName + COMPONENT_NAME),
						PackageManager.COMPONENT_ENABLED_STATE_DISABLED,
						PackageManager.DONT_KILL_APP);

**Comment by jahirfiquitiva** [comment]
@AkshayChordiya
Yeah, code is already in the app and works fine for me.

**Comment by asdfasdfvful** [comment]
I haven't had time to look at this yet.

**Comment by AllanWang** [comment]
This should be closed soon. I also believe that both the removal and showing of the icon should depend on the fullname string only. The _name would should be removed. You are using it now in a try catch so it's up to you if you want to remove it or not.
