### ISSUE TITLE
LandScape Mode: TabLayout overlaps toolbar at icon screen on Android 4.4 and below

### ISSUE THREAD

**Issue by DanteNguyen1008** [jahirfiquitiva/IconShowcase#91]
hi man,

Thanks for the super useful library. it saves my days. but currently I am having issue at Icon screen.

The TabLayout overlaps toolbar on LandScape mode on Android 4.4 and below. 

Do you have any idea about that?  I checked the sample and some other apps made by IconShowcase, they have same issue. 

![screen shot 2016-04-12 at 8 46 52 pm](https://cloud.githubusercontent.com/assets/3113106/14479761/e05dbf2a-00ef-11e6-928f-557f778dcae3.png)

Thanks

**Comment by jahirfiquitiva** [comment]
I'm not able to reproduce the issue.

Are you using the library source? Or the dashboard source?

**Comment by DanteNguyen1008** [comment]
thx for the fast response. I am using the dashboard sample source.

**Comment by jahirfiquitiva** [comment]
So you are taking the source from
http://github.com/jahirfiquitiva/IconShowcase-Dashboard ... right?

1. I want to ask you to post issues in that site.

2. Well, I haven't updated the library source for about a month. Until a couple weeks ago, we had to use a "workaround" to fix the TabLayout behavior, which I think is not "official" yet.

A new update of the library will be available in a couple days, and it may fix the issue.

So, for now, please wait until that release. Then test, and if it still happens, post the issue again.

Also, join the community to stay tuned about updates and get help (maybe) even faster.
