### ISSUE TITLE
Requested Icon Resolution

### ISSUE THREAD

**Issue by amin947** [jahirfiquitiva/IconShowcase#93]
Hello there
I have a problem with the dashboard. The problem is that the resolution of the requested icons (in the zip file) is based on the device from which the request is sent. For example, I received emails that the icons (in the attached zip file of the request email) are in low resolution such as 96x96, 144x144, etc.
I always want the high resolution icons (192x192) from all users (without considering their phone/tablet resolution).
Is it possible? What should I do?

**Comment by jahirfiquitiva** [comment]
I will try to fix it for a future update. There's nothing you can do about it for now.

If you are using the library source, you can try to fix it for yourself and make a pull request so the fix will be available for everyone.

Otherwise all you can do it wait for next update.

**Comment by amin947** [comment]
Thanks for your fast response.
I think I don't have enough knowledge to help this problem be solved.
So, I should wait for the future updates :)

**Comment by AllanWang** [comment]
https://github.com/AllanWang/Icon-Request-Tool/blob/master/PkRequestManager/src/main/java/com/pkmmte/requestmanager/PkRequestManager.java#L1455

Please see this

**Comment by jahirfiquitiva** [comment]
@AllanWang

Already used a similar code. Haven't committed it though.

**Comment by jahirfiquitiva** [comment]
Fixed with latest commit.

**Comment by amin947** [comment]
Thanks so much

**Comment by amin947** [comment]
Hi again
For some issues, I do not want to go to dashboard v1.8.3.
Could you tell me please what exactly should I modify to solve this icon resolution issue in dashboad v1.6 ?
Thanks in advance

**Comment by AllanWang** [comment]
@amin947 for what reason do you not with to update? If you know how to code, it's probably [this section](https://github.com/jahirfiquitiva/IconShowcase/blob/master/showcase/src/main/java/jahirfiquitiva/iconshowcase/tasks/LoadAppsToRequest.java#L338), but it would honestly be easier for you to update everything and copy your strings and configurations again than to merge the code in.

**Comment by jahirfiquitiva** [comment]
@amin947
Why do you want to update? What are the issues you have?
