### ISSUE TITLE
Icon Request Tool doesn't seem to be working

### ISSUE THREAD

**Issue by AllanWang** [jahirfiquitiva/IconShowcase#94]
At least in my current build it isn't working. I will check it out later on.

Additionally, it might be nice to add an option to show the requests without filtering with the appfilter. Often times, icons will be themed but are outdated, so there should be a way to send the original icons of already themed apps (should be a hidden feature though).

**Comment by jahirfiquitiva** [comment]
Is working fine for me. What's exactly not working?

About that option, I won't do it. If people notice an app with an updated icon they must contact the designer about it.

I'm going to remove some other options as I want to provide a customizable dashboard but easy to setup too. Don't know which options I will delete yet, but I will.

**Comment by AllanWang** [comment]
For me, if I tap a card, nothing is happening, so I can't seem to send requests. I redid my app directly with the latest source so I'll have to check out what is wrong.

In regards to removing options, I think one thing to remove would be the icon changelog. I think most themers update with at least a few dozen icons each time, and it's much easier to view it with a "new" tab under the icon list than to see the icons in a dialog. Just an idea.

**Comment by jahirfiquitiva** [comment]
Fixed with latest commit
