### ISSUE TITLE
Make license checker work always and better or properly

### ISSUE THREAD

**Issue by jahirfiquitiva** [jahirfiquitiva/IconShowcase#96]
With always I mean always, but if designers enable it in the dashboard.

**Comment by AllanWang** [comment]
"With always I mean always", what do you mean by this? We can still disable it right?

**Comment by jahirfiquitiva** [comment]
@AllanWang  I mean always if enabled... because it seems to have some issues yet.
As reported [here](https://plus.google.com/+LeonardoMazzone94/posts/4ikcxyeM6n6)

**Comment by AllanWang** [comment]
https://github.com/jahirfiquitiva/IconShowcase/blob/master/showcase/src/main/java/jahirfiquitiva/iconshowcase/activities/ShowcaseActivity.java#L683

If there is an installer (the internet) and it's not licensed, you currently have no action running. Add another else with showNotLicensedDialog

**Comment by jahirfiquitiva** [comment]
OMG @AllanWang  how did I miss this one?

Let me try and make an user test it.

If fixed I will close the issue.

Thank you so much <3

**Comment by AllanWang** [comment]
Yeah it's easy to test. Just publish as a release.apk and install that. It should have an installer then as it isn't through adb

**Comment by AllanWang** [comment]
My suggestion

```java
try {
	if (installer != null) {
		installedFromPlayStore = (installer.matches("com.google.android.feedback") || installer.matches("com.android.vending"));
		if (mPrefs.isFirstRun()) {
			if (installedFromPlayStore || (installer.matches("com.amazon.venezia") && WITH_INSTALLED_FROM_AMAZON)) {
				licenseSuccessDialog().show();
				return;
			}
		}
	}
	showNotLicensedDialog((Activity) context, mPrefs, MARKET_URL);
            
} catch (Exception e) {
	Utils.showLog(context, "Error checking license: " + e.getLocalizedMessage());
	showNotLicensedDialog((Activity) context, mPrefs, MARKET_URL);
}

```

**Comment by jahirfiquitiva** [comment]
@AllanWang  thank you..

I think is working now.. let's wait a couple of days for some people to actually test it.

**Comment by jahirfiquitiva** [comment]
Seems like apps like Lucky Patcher or similar are able to modify the code and make the app work normally...

**Comment by asdfasdfvful** [comment]
I don't know how  lucky patcher works exactly but Im not sure if there is a wok around unless you change the way you check your license. Since the license activates when you buy an in app purchase (at least so I assume), you can check if the in App purchase exists rather than checking if it is installed from the play store. 

If it's a free app on the play store, it probably doesn't matter as much where the user installs it

**Comment by jahirfiquitiva** [comment]
Found a good library...

https://github.com/javiersantos/PiracyChecker
